'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

'
'This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
'
Namespace HRDLogGrids
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType", [Namespace]:="http://schemas.datacontract.org/2004/07/HRDLogBookService")>  _
    Partial Public Class CompositeType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private BoolValueField As Boolean
        
        Private StringValueField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BoolValue() As Boolean
            Get
                Return Me.BoolValueField
            End Get
            Set
                If (Me.BoolValueField.Equals(value) <> true) Then
                    Me.BoolValueField = value
                    Me.RaisePropertyChanged("BoolValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StringValue() As String
            Get
                Return Me.StringValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StringValueField, value) <> true) Then
                    Me.StringValueField = value
                    Me.RaisePropertyChanged("StringValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GridReached", [Namespace]:="http://schemas.datacontract.org/2004/07/HRDLogBookService")>  _
    Partial Public Class GridReached
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private BandField As String
        
        Private CallsignField As String
        
        Private DistanceField As Decimal
        
        Private GridSquareField As String
        
        Private MH2Field As String
        
        Private ModeField As String
        
        Private ShapeField As HRDLogGrids.DbGeometry
        
        Private syncidField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Band() As String
            Get
                Return Me.BandField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BandField, value) <> true) Then
                    Me.BandField = value
                    Me.RaisePropertyChanged("Band")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Callsign() As String
            Get
                Return Me.CallsignField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CallsignField, value) <> true) Then
                    Me.CallsignField = value
                    Me.RaisePropertyChanged("Callsign")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Distance() As Decimal
            Get
                Return Me.DistanceField
            End Get
            Set
                If (Me.DistanceField.Equals(value) <> true) Then
                    Me.DistanceField = value
                    Me.RaisePropertyChanged("Distance")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GridSquare() As String
            Get
                Return Me.GridSquareField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GridSquareField, value) <> true) Then
                    Me.GridSquareField = value
                    Me.RaisePropertyChanged("GridSquare")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MH2() As String
            Get
                Return Me.MH2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.MH2Field, value) <> true) Then
                    Me.MH2Field = value
                    Me.RaisePropertyChanged("MH2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Mode() As String
            Get
                Return Me.ModeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ModeField, value) <> true) Then
                    Me.ModeField = value
                    Me.RaisePropertyChanged("Mode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Shape() As HRDLogGrids.DbGeometry
            Get
                Return Me.ShapeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ShapeField, value) <> true) Then
                    Me.ShapeField = value
                    Me.RaisePropertyChanged("Shape")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property syncid() As String
            Get
                Return Me.syncidField
            End Get
            Set
                If (Object.ReferenceEquals(Me.syncidField, value) <> true) Then
                    Me.syncidField = value
                    Me.RaisePropertyChanged("syncid")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DbGeometry", [Namespace]:="http://schemas.datacontract.org/2004/07/System.Data.Entity.Spatial")>  _
    Partial Public Class DbGeometry
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private GeometryField As HRDLogGrids.DbGeometryWellKnownValue
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Geometry() As HRDLogGrids.DbGeometryWellKnownValue
            Get
                Return Me.GeometryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GeometryField, value) <> true) Then
                    Me.GeometryField = value
                    Me.RaisePropertyChanged("Geometry")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DbGeometryWellKnownValue", [Namespace]:="http://schemas.datacontract.org/2004/07/System.Data.Entity.Spatial")>  _
    Partial Public Class DbGeometryWellKnownValue
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private CoordinateSystemIdField As Integer
        
        Private WellKnownTextField As String
        
        Private WellKnownBinaryField() As Byte
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property CoordinateSystemId() As Integer
            Get
                Return Me.CoordinateSystemIdField
            End Get
            Set
                If (Me.CoordinateSystemIdField.Equals(value) <> true) Then
                    Me.CoordinateSystemIdField = value
                    Me.RaisePropertyChanged("CoordinateSystemId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property WellKnownText() As String
            Get
                Return Me.WellKnownTextField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WellKnownTextField, value) <> true) Then
                    Me.WellKnownTextField = value
                    Me.RaisePropertyChanged("WellKnownText")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property WellKnownBinary() As Byte()
            Get
                Return Me.WellKnownBinaryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WellKnownBinaryField, value) <> true) Then
                    Me.WellKnownBinaryField = value
                    Me.RaisePropertyChanged("WellKnownBinary")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="HRDLogGrids.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetData", ReplyAction:="http://tempuri.org/IService1/GetDataResponse")>  _
        Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IService1/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContractAsync(ByVal composite As HRDLogGrids.CompositeType) As System.Threading.Tasks.Task(Of HRDLogGrids.CompositeType)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getGridsReached", ReplyAction:="http://tempuri.org/IService1/getGridsReachedResponse")>  _
        Function getGridsReachedAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HRDLogGrids.GridReached))
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits HRDLogGrids.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of HRDLogGrids.IService1)
        Implements HRDLogGrids.IService1
        
        ''' <summary>
        ''' Implement this partial method to configure the service endpoint.
        ''' </summary>
        ''' <param name="serviceEndpoint">The endpoint to configure</param>
        ''' <param name="clientCredentials">The client credentials</param>
        Partial Private Shared Sub ConfigureEndpoint(ByVal serviceEndpoint As System.ServiceModel.Description.ServiceEndpoint, ByVal clientCredentials As System.ServiceModel.Description.ClientCredentials)
        End Sub
        
        Public Sub New()
            MyBase.New(Service1Client.GetDefaultBinding, Service1Client.GetDefaultEndpointAddress)
            Me.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration)
            MyBase.New(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration, ByVal remoteAddress As String)
            MyBase.New(Service1Client.GetBindingForEndpoint(endpointConfiguration), New System.ServiceModel.EndpointAddress(remoteAddress))
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String) Implements HRDLogGrids.IService1.GetDataAsync
            Return MyBase.Channel.GetDataAsync(value)
        End Function
        
        Public Function GetDataUsingDataContractAsync(ByVal composite As HRDLogGrids.CompositeType) As System.Threading.Tasks.Task(Of HRDLogGrids.CompositeType) Implements HRDLogGrids.IService1.GetDataUsingDataContractAsync
            Return MyBase.Channel.GetDataUsingDataContractAsync(composite)
        End Function
        
        Public Function getGridsReachedAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HRDLogGrids.GridReached)) Implements HRDLogGrids.IService1.getGridsReachedAsync
            Return MyBase.Channel.getGridsReachedAsync
        End Function
        
        Public Overridable Function OpenAsync() As System.Threading.Tasks.Task
            Return System.Threading.Tasks.Task.Factory.FromAsync(CType(Me,System.ServiceModel.ICommunicationObject).BeginOpen(Nothing, Nothing), AddressOf CType(Me,System.ServiceModel.ICommunicationObject).EndOpen)
        End Function
        
        Public Overridable Function CloseAsync() As System.Threading.Tasks.Task
            Return System.Threading.Tasks.Task.Factory.FromAsync(CType(Me,System.ServiceModel.ICommunicationObject).BeginClose(Nothing, Nothing), AddressOf CType(Me,System.ServiceModel.ICommunicationObject).EndClose)
        End Function
        
        Private Shared Function GetBindingForEndpoint(ByVal endpointConfiguration As EndpointConfiguration) As System.ServiceModel.Channels.Binding
            If (endpointConfiguration = EndpointConfiguration.BasicHttpBinding_IService1) Then
                Dim result As System.ServiceModel.BasicHttpBinding = New System.ServiceModel.BasicHttpBinding()
                result.MaxBufferSize = Integer.MaxValue
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max
                result.MaxReceivedMessageSize = Integer.MaxValue
                result.AllowCookies = true
                Return result
            End If
            Throw New System.InvalidOperationException(String.Format("Could not find endpoint with name '{0}'.", endpointConfiguration))
        End Function
        
        Private Shared Function GetEndpointAddress(ByVal endpointConfiguration As EndpointConfiguration) As System.ServiceModel.EndpointAddress
            If (endpointConfiguration = EndpointConfiguration.BasicHttpBinding_IService1) Then
                Return New System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/HRDLogBookService/Service1/")
            End If
            Throw New System.InvalidOperationException(String.Format("Could not find endpoint with name '{0}'.", endpointConfiguration))
        End Function
        
        Private Shared Function GetDefaultBinding() As System.ServiceModel.Channels.Binding
            Return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1)
        End Function
        
        Private Shared Function GetDefaultEndpointAddress() As System.ServiceModel.EndpointAddress
            Return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1)
        End Function
        
        Public Enum EndpointConfiguration
            
            BasicHttpBinding_IService1
        End Enum
    End Class
End Namespace
